name: SpotConnect
version: "0.20.8-8"
slug: spotconnect
description: Make AirPlay devices available as Spotify Connect devices
url: "https://github.com/Allcrafter1/ha-spotconnect"
arch:
  - aarch64
  - amd64
init: false
host_network: true
options:
  airplay_enabled: true
  upnp_enabled: false
  network_interface: ""
  bitrate: "320"
  name_format: "%s+"
  store_credentials: true
  log_level: info
  airplay_codec: alac
  upnp_codec: flc
schema:
  airplay_enabled: bool
  upnp_enabled: bool
  network_interface: str?
  bitrate: list(96|160|320)
  name_format: str(1,80)
  store_credentials: bool
  log_level: list(error|warn|info|debug|sdebug)
  airplay_codec: list(alac|pcm)
  upnp_codec: str
image: "ghcr.io/allcrafter1/ha-spotconnect"
